routes/web.php
<?php

use App\Http\Controllers\AccountController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('bankocr.index');
});
Route::resource('accounts', AccountController::class);

resources/views/bankocr/index.blade.php
@extends('layouts.app')

@section('title', 'Read file')
@section('content')
    <div class="row justify-content-center p-5">
        <div class="col-6">
            <h1>Bank OCR</h1>
            <p>Upload your file and read bank accounts.</p>
            <form method="post" enctype="multipart/form-data" action="{{route('accounts.store')}}">
                @csrf
                <div class="input-group">
                    <input type="file" class="form-control @error('accounts') is-invalid @enderror" id="accounts" name="accounts" aria-describedby="accounts" aria-label="Upload">
                    <button class="btn btn-outline-secondary" type="submit" id="accounts">Submit</button>
                </div>
                @error('accounts')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </form>
        </div>
    </div>
@endsection

resources/views/bankocr/results.blade.php
@extends('layouts.app')

@section('title', 'Read file')
@section('content')
    <div class="row justify-content-center p-5">
        <div class="col-6">
            <h1>Bank OCR</h1>
            <p>Results of uploaded file.</p>
            <pre>
                {{$renderOCR}}
            </pre>
            <p><a href="{{$file}}">Pobierz raport</a></p>
            <p>The execution time of the PHP script is : {{$execution_time}} sec</p>
        </div>
    </div>
@endsection